* First Entry [2019-10-31 Thu]
A friend gave me the idea to work on a passion project to prove to myself and others that I have the passion to go down a data scientist path. For the project I decided to work on something that I was interested in, as well as being able to showcase some of the skills which I've picked up along the way. The topic which I decided on pursuing was a machine learning model for football match outcome prediction. I've given myself 3 months to complete this project.

To date, I have completed a basic project plan, with multiple milestones and deadlines for completing the project. I've also began to do some preliminary investigation on previous works which have been done on predicting the outcome of football matches.

I am committing to regularly updating this logbook and making commits to this github repository in order to keep up the momementum for this project.
* Investigated features [2019-11-01 Fri]
As I was polishing my project plan, I had the idea to expand the scope beyond just predicting individual football matches, but to include an AI strategy for a tipping competition. This will also allow me to practice some of the AI algorithms which I learned on my exchange to the US.

I also began documenting some high-level drivers for the model. The main themes behind the features were:
- Past performances
- Mentality
- Environment
- Schedule
- Team
- Manager
- Fanbase
* Feature table [2019-11-03 Sun]
I spent the majority of yesterday converting the drivers to features which I am collating on a google sheet. Currently I have over 100 features.

I've also found a few websites which have football statistics going back multiple seasons. Most useful one I've found is here: [[http://www.football-data.co.uk/][football-data.uk]]. I began work on a simple script to pull the data from the website into a csv.

Next steps:
- Continue work on downloading data from football website
- Go through feature list and evaluate them based on: availability, importance, etc...
- Do initial data exploration to qualify the features
* Scraping football scores [2019-11-05 Tue]
Today I worked on a webscraper to download csv files from here: [[http://www.football-data.co.uk/englandm.php][football-data.uk]]. I used /BeautifulSoup/ python package to scrape the links to flat files that I wanted to download off the website, and then the /requests/ library to download the CSV files to my computer. The script which I ran is on the gitbub repository.
* Exploring football data [2019-11-06 Wed]
I began exploring the football data which I extracted yesterday. I'm using R-studio to do my exploration. So far I've looked at the distribution for some of the primary statistics such as:
- Corners taken per game
- Number of shots
- Number of goals

A few interesting factors to consider are that EPL and EFL Championship leagues have different distributions (particularly noticeable in the case of fouls per game). Another thing to look out for is variation of stats between seasons, for example in 18-19 season there were a lot fewer games drawn as opposed to previous years. Final thing to note is that a lot of the stats appear to be normally distributed.

I also made some progress on extracting some of the features. I've made some headway into extracting the last 3 match results as a factor (i.e. WWW, WWL, WLL, ...). Progress can be seen in the github repository.
* Analysing effect of past results [2019-11-08 Fri]
Today I spent more time/effort on getting the past /n/ results as a feature. I then did some some exploration and found a strong correlation between 2+ Wins out of the last 3 resulting in a win. I also completed my project timeline and plan which I have submitted for a review.
* Ingesting > Feature Engineering > Analysis [2019-11-18 Mon]
I haven't been consistent with updating the logbook and committing to github, however I haven't been idle either. 

My update is as follows:
- Decided on a framework which uses the following tools:
  - Data mining and ingestion: Python + TinyDB
  - Feature engineering: Python + TinyDB + Pandas
  - Feature analysis and data exploration: R

I'm learning lots of new tools in Python for data mining and ingesting, including: BeautifulSoup, TinyDB.

I'm also learning to use best practices, including: importing my own functions, functional programming (helper functions and main function).
* First model complete [2019-12-02 Mon]
Today was a super busy day. I was able to complete the first iteration of the model which had a *49% accuracy* using a decision tree classifier based on a 80/20 split of training and test data. This is a lift of 16% from random guessing.

Things that I did today/last night to achieve this:
- Feature engineering (128 features)
- One-hot-encoding
- Training and testing model

Next steps:
- Create Python library for feature engineering
- Add additional features
- Refine training model
* AI algorithm notes [2019-12-26 Thu]
I am considering which AI algorithm to use as a betting strategy. My research has led me to consider stochastic game theory which only uses a static strategy which only considers the current state.
