* First Entry [2019-10-31 Thu]
A friend gave me the idea to work on a passion project to prove to myself and others that I have the passion to go down a data scientist path. For the project I decided to work on something that I was interested in, as well as being able to showcase some of the skills which I've picked up along the way. The topic which I decided on pursuing was a machine learning model for football match outcome prediction. I've given myself 3 months to complete this project.

To date, I have completed a basic project plan, with multiple milestones and deadlines for completing the project. I've also began to do some preliminary investigation on previous works which have been done on predicting the outcome of football matches.

I am committing to regularly updating this logbook and making commits to this github repository in order to keep up the momementum for this project.
* Investigated features [2019-11-01 Fri]
As I was polishing my project plan, I had the idea to expand the scope beyond just predicting individual football matches, but to include an AI strategy for a tipping competition. This will also allow me to practice some of the AI algorithms which I learned on my exchange to the US.

I also began documenting some high-level drivers for the model. The main themes behind the features were:
- Past performances
- Mentality
- Environment
- Schedule
- Team
- Manager
- Fanbase
* Feature table [2019-11-03 Sun]
I spent the majority of yesterday converting the drivers to features which I am collating on a google sheet. Currently I have over 100 features.

I've also found a few websites which have football statistics going back multiple seasons. Most useful one I've found is here: [[http://www.football-data.co.uk/][football-data.uk]]. I began work on a simple script to pull the data from the website into a csv.

Next steps:
- Continue work on downloading data from football website
- Go through feature list and evaluate them based on: availability, importance, etc...
- Do initial data exploration to qualify the features
