---
title: "Feature Engineering"
output: html_notebook
---

```{r include=FALSE}
rm(list=ls())
library(tidyverse)
```

```{r}
loadData <- function(year_code, division) {
  ret_tbl <- tibble()
  for (yc in year_code) {
    for (div in division) {
      fname <- paste("../Data/",yc,"_",div,".csv",sep="")
      tmp_tbl <- read_csv(fname) %>%
        mutate(Season=yc,Date=as.Date(Date,format="%d/%m/%Y"))
      ret_tbl <- bind_rows(ret_tbl,tmp_tbl)
    }
  }
  return(ret_tbl)
}
filterTeam <- function(dat,team_name) {
  return(filter(dat,HomeTeam==team_name|AwayTeam==team_name))
}
filterTeamResult <- function(dat,team_name,home_away=c("H","A")){
  filtered_dat <- filterTeam(dat,team_name)
  result_dat <- filtered_dat %>%
    mutate(TM_Team = team_name) %>%
    mutate(TM_FTR = case_when(
      HomeTeam==team_name & FTR=="H" ~ "W",
      AwayTeam==team_name & FTR=="A" ~ "W",
      FTR=="D" ~ "D",
      TRUE ~ "L")
    ) %>%
    arrange(desc(Date))
  return(result_dat)
}
```

```{r}
all_data <- loadData(c("1819","1718","1617"),c("E0","E1"))
all_data
```

