---
title: "Exploring Football Data"
output:
  html_document:
    df_print: paged
---

```{r include=FALSE}
rm(list=ls())
library(tidyverse)
```

```{r}
loadData <- function(year_code, division) {
  ret_tbl <- tibble()
  for (yc in year_code) {
    for (div in division) {
      fname <- paste("../Data/",yc,"_",div,".csv",sep="")
      tmp_tbl <- read_csv(fname) %>%
        mutate(Season=yc,Date=as.Date(Date,format="%d/%m/%Y"))
      ret_tbl <- bind_rows(ret_tbl,tmp_tbl)
    }
  }
  return(ret_tbl)
}
filterTeam <- function(dat,team_name) {
  return(filter(dat,HomeTeam==team_name|AwayTeam==team_name))
}
filterTeamResult <- function(dat,team_name,home_away=c("H","A")){
  filtered_dat <- filterTeam(dat,team_name)
  result_dat <- filtered_dat %>%
    mutate(TM_Team = team_name) %>%
    mutate(TM_FTR = case_when(
      HomeTeam==team_name & FTR=="H" ~ "W",
      AwayTeam==team_name & FTR=="A" ~ "W",
      FTR=="D" ~ "D",
      TRUE ~ "L")
    ) %>%
    arrange(desc(Date))
  return(result_dat)
}
```

```{r message=FALSE}
all_data <- loadData(c("1819","1718","1617"),c("E0","E1"))
fulham_data <- filterTeamResult(all_data,"Fulham")
fulham_data
```

```{r}
ggplot(all_data, aes(x=FTR,fill=FTR)) +
  geom_bar() +
  facet_grid(rows=vars(Div),cols=vars(Season)) +
  ggtitle("Full Time Results")
```

```{r}
ggplot(all_data,aes(x=FTHG+FTAG)) +
  geom_bar() +
  facet_grid(rows=vars(Div)) + 
  ggtitle("Number of Goals Scored")
```

```{r}
ggplot(all_data,aes(x=HS+AS)) +
  geom_bar() +
  facet_grid(rows=vars(Div)) + 
  ggtitle("Number of Shots")
```

```{r}
ggplot(all_data,aes(x=abs(FTHG-FTAG))) +
  geom_bar() +
  facet_grid(rows=vars(Div)) +
  ggtitle("Goal Differences")
```

```{r}
ggplot(all_data,aes(x=HC+AC)) +
  geom_bar() +
  facet_grid(rows=vars(Div)) + 
  ggtitle("Number of Corners")
```

```{r}
ggplot(all_data,aes(x=HF+AF)) +
  geom_bar() +
  facet_grid(rows=vars(Div)) + 
  ggtitle("Number of Fouls")
```

```{r}
home_result <- all_data %>%
  mutate(
    TeamName=HomeTeam,
    HomeAway = "Home",
    Result = case_when(
      FTR == "H" ~ "W",
      FTR == "D" ~ "D",
      FTR == "A" ~ "L"
    )
  ) %>%
  select(c("Date","TeamName","HomeAway","Result"))
away_result <- all_data %>%
  mutate(
    TeamName=AwayTeam,
    HomeAway = "Away",
    Result = case_when(
      FTR == "H" ~ "L",
      FTR == "D" ~ "D",
      FTR == "A" ~ "W"
    )
  ) %>%
  select(c("Date","TeamName","HomeAway","Result"))
all_result <- rbind(home_result,away_result) %>%
  arrange(desc(Date))
tmp <- all_result %>%
  arrange(desc(Date)) %>%
  group_by(TeamName) %>%
  mutate(
    rank1 = row_number(),
    rank2 = row_number()-1,
    rank3 = row_number()-2,
    rank4 = row_number()-3,
    rank5 = row_number()-4,
    rank6 = row_number()-5,
    rank7 = row_number()-6,
    rank8 = row_number()-7,
    rank9 = row_number()-8,
    rank10 = row_number()-9,
    rank11 = row_number()-10
  ) %>%
  select(c("Date","TeamName","HomeAway","Result","rank1","rank2","rank3","rank4",
           "rank5","rank6","rank7","rank8","rank9","rank10","rank11"))
tmp1 <- tmp %>%
  select(c("Date","TeamName","HomeAway","Result","rank1"))
tmp2 <- tmp %>%
  mutate(Result2=Result) %>%
  select(c("TeamName","Result2","rank2"))
tmp3 <- tmp %>%
  mutate(Result3=Result) %>%
  select(c("TeamName","Result3","rank3"))
tmp4 <- tmp %>%
  mutate(Result4=Result) %>%
  select(c("TeamName","Result4","rank4"))
tmp5 <- tmp %>%
  mutate(Result5=Result) %>%
  select(c("TeamName","Result5","rank5"))
tmp6 <- tmp %>%
  mutate(Result6=Result) %>%
  select(c("TeamName","Result6","rank6"))

last_n_result <- tmp1 %>%
  left_join(tmp2,by=c("TeamName"="TeamName","rank1"="rank2")) %>%
  left_join(tmp3,by=c("TeamName"="TeamName","rank1"="rank3")) %>%
  left_join(tmp4,by=c("TeamName"="TeamName","rank1"="rank4")) %>%
  left_join(tmp5,by=c("TeamName"="TeamName","rank1"="rank5")) %>%
  left_join(tmp6,by=c("TeamName"="TeamName","rank1"="rank6")) %>%
  mutate(last_3_results = paste(Result2,Result3,Result4,sep=""))

last_n_result
```

```{r}
plt_dat <- last_n_result %>%
  filter(!grepl("NA",last_3_results))
plt_dat
```

```{r}
ggplot(data=plt_dat, aes(x=fct_reorder(last_3_results,Result=="W",mean,.desc=TRUE),fill=ordered(Result, levels=c("L","D","W")))) +
  geom_bar(position="fill") +
  ggtitle("Current Result vs. Last 3 Results")
```




